version: "3"
services:
  ppi-karabuk-blog:
    container_name: PPI-Karabuk-Blog
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: ppi-karabuk-blog:latest
    restart: unless-stopped
    env_file: .env
    environment:
      HOST: ${HOST}
      PORT: ${PORT}
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_URL: ${DATABASE_URL}
      SUPABASE_API_URL: ${SUPABASE_API_URL}
      SUPABASE_API_KEY: ${SUPABASE_API_KEY}
      SUPABASE_BUCKET: ${SUPABASE_BUCKET}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock

      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
